services:
  account-bot:
    image: dystian/microsoft-account-bot:latest
    shm_size: '2gb'
    container_name: microsoft-account-bot
    restart: always
    network_mode: host
    env_file: .env
    environment:
      - DISPLAY=:20
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /home/zulpanpratama/.Xauthority:/root/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
